### ISSUE TITLE
Standard Properties in Copy and Paste Code Too?

### ISSUE THREAD

**Issue by chriscoyier** [henripar/scrollbar#1]
I know it wouldn't yield one-to-one output, but as you mention...

>  For other browsers, you can use the scrollbar selectors provided by the W3C, such as scrollbar-width, scrollbar-color, scrollbar-track-color, scrollbar-thumb-color, and scrollbar-face-color.

Since people are picking colors, and the output style is pretty basic, seems to me you might as well chuck the couple relevant standardized properties in the copy and paste code section too.

Bonus: put the colors into `--scrollbar-color` custom properties to keep it DRY.

**Comment by henripar** [comment]
Great points! I actually already thought about adding those into the code output but since these properties must be added to some element the code output wouldn't be as universal since people might want to use them on different elements. eg.

```
div / .custom-scrollbar / body {
scrollbar-color: #fff #000;
}
````
Since I wasn't sure what would be the best way to implement this in a way that would lead to best user experience I decided to put that on hold until I come up with a good way to implement it. 

Any thoughts on what would be a good way on adding them to code output that would lead to best user experience?

**Comment by chriscoyier** [comment]
Good point!

I would think *most* usage would be on the body. So if you scoped *all* the CSS like that, maybe that's a good hint to everyone that the selector can be changed?

```
body {
  --scrollbar-foreground: white;
  --scrollbar-background: black;
  --scrollbar-size: 20px;

  scrollbar-color: var(--scrollbar-foreground) var(--scrollbar-background);
}
body::-webkit-scrollbar {
  width: var(--scrollbar-size);
  height: var(--scrollbar-size);
}
body::-webkit-scrollbar-thumb {
  background: var(--scrollbar-foreground);
  border-radius: 100px;
}
body::-webkit-scrollbar-track {
  background: var(--scrollbar-background);
}
```

I dunno. It's not that big of a deal, it just seems like there will be an eventual march toward standards here and even now, Firefox people would benefit.

**Comment by henripar** [comment]
Yeah, thats probably the best way to do it.

Thanks for your input Chris! I went with your suggestion and used `body` as a base.
