### ISSUE TITLE
pls make light version

### ISSUE THREAD

**Issue by diomed** [henripar/scrollbar#12]
please make white background version these days one can switch between light/dark background.

you should improve your app to do that with bg as well

**Comment by henripar** [comment]
Sure, I can do that when I have some free time on my hands. At the moment I am busy with other things though.
Until then, if anyone else have time and want to implement that, feel free to make a PR 😄

**Comment by diomed** [comment]
since this isnt something urgent, if you dont fix it by hacktober, I'll leave it till hacktoberfest 🙂 
unless someone tackles it before. (which i doubt, lol)

**Comment by haaarsh619** [comment]
Hello i want to work on this issue. Can i ?
if yes we need something like this 
![image](https://github.com/henripar/scrollbar/assets/72140070/42a649e4-f019-449d-bd17-143822aba4f6)

**Comment by diomed** [comment]
> Hello i want to work on this issue. Can i ? if yes we need something like this ![image](https://user-images.githubusercontent.com/72140070/268519591-42a649e4-f019-449d-bd17-143822aba4f6.png)

of course you can.

**Comment by henripar** [comment]
@haaarsh619 Feel free to implement. Personally, I think it might be good idea to add some background color for the main elements as well for the light version in order to get clearer separation for the elements. For example something like this.. 
![Screenshot 2023-09-17 at 22 09 11](https://github.com/henripar/scrollbar/assets/55137381/5fc3b262-6d3e-4ef8-98e1-a4ec1f55b421)
